### ISSUE TITLE
Remove import from spec

### ISSUE THREAD

**Issue by svarlamov** [exlskills/exl-open-courseware-standard#2]
It was a good idea when we started, but for the time being, we are sticking to 100% plain vanilla markdown. Such as the case, it's best that we remove the import spec until we are ready to consider how we would manage the developer/instructor experience around that.

Also, there is no longer a need for this part of the spec, since you can setup multiple blocks within a vertical using multiple files/REPLs (ref #1)

**Comment by Hellboy1008** [comment]
Custom import sequence removed
